# Generated by Django 2.0.7 on 2018-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='job_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='tyre_guage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
